### ISSUE TITLE
September Agenda

### ISSUE THREAD

**Issue by lynnaloo** [norfolkjs/logistics#97]
September 19th

Food Sponsor: Langa
Beer Sponsor: 80/20 Consoluting
Location Sponsor: Pierce/McCoy
Events: HrDevFest, Revolution Conf (June 1-2), PopUp Robots, Fez

Feature Presentation: Travis Webb - API Driven Development with TrailsJS
Lightning Talk(s): Brandon about NodeBots Day

**Comment by lynnaloo** [comment]
@bmf @troy0820 I know ya'll both have lightning talks coming up at HRNUG. Do you want to add to announcements?

**Comment by troy0820** [comment]
Yes, we can add it to the announcements.  I think it'll be good.

**Comment by bmf** [comment]
http://rawgit.com/norfolkjs/general-info/master/announcements/september_2016.html

Announcements are done. I left off the lightning talks because Troy did his prior to this meetup and mine isn't until april, 2017. I'd also like to do one @ Norfolk JS around the same time if possible. The topic will be a sneak peek into our plans for Intl Nodebotsday 2017.
